### ISSUE TITLE
Critical error on gemini update

### ISSUE THREAD

**Issue by apsavin** [researchgate/gemini-react#31]
Hi!

Thanks for your plugin! I know, it's not production-ready, but I'm interested in such functionality and I checked if I'll be able to use it with popular [RSK](https://github.com/kriasoft/react-starter-kit)

It seems that there is an error in gemini-babel or gemini-react:

```
$ ./node_modules/.bin/gemini update
Critical error:
SyntaxError: Unexpected token import
/Users/savin/PhpstormProjects/react-starter-kit/tools/webpack.config.js:10
import path from 'path';
^^^^^^
```

You can easily reproduce it using [this](https://github.com/apsavin/react-starter-kit/tree/gemini-react) code

**Comment by SevInf** [comment]
Hi. I'm sorry a bit late response. It is looks like `gemini-react` plugin is executed before `gemini-babel`, so you can not use ES6 in webpack config yet. Can you try swapping the order of the plugins in `.gemini.yml`?

**Comment by apsavin** [comment]
Thanks for the response!
It helps, but not much:

```
Critical error:
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'default'.
```
I thought it's because of `export default [clientConfig, serverConfig]` line in webpack.config.js and created a special version of webpack configuration for gemini:

```js
const configs = require('./webpack.config');
module.exports = configs[0];
```
It helped.

But now I have an error on a page in browser:
![2017-04-05 12 55 51](https://cloud.githubusercontent.com/assets/632171/24700398/b73550ac-19ff-11e7-8689-9aa854c74c71.png)

I can't get the full message, because selenium closes the browser window too quickly and gemeni does not create error shots. Could you please give me an advice, how to figure out what's the problem (actual code [here](https://github.com/apsavin/react-starter-kit/tree/gemini-react))?

**Comment by SevInf** [comment]
You can launch server via `./node_modules/.bin/gemini-react-server` and naviagate to the same url, that way it won't close.
Note, that Gemini tests also must pass through `babel-loader` during webpack build (without going into much internal details, `gemini-babel` affects only server-side part), but your config [includes only /src dir](https://github.com/apsavin/react-starter-kit/blob/gemini-react/tools/webpack.config.js#L54). Adding gemini tests directory to the list should fix the problem.

**Comment by apsavin** [comment]
> You can launch server via `./node_modules/.bin/gemini-react-server` and navigate to the same url

Great, should be in the docs definitely.

Thanks for your help! It works now.
