### ISSUE TITLE
Example doesn't work: Could not find element

### ISSUE THREAD

**Issue by dmitrika** [researchgate/gemini-react#32]
Hello!

Trying your plugin and faced trouble. My test file looks like:

```
import React from 'react';

geminiReact.suite('my react test', suite => {
    suite.render(<div>Hello world</div>).capture('initial');
});
```

And problem after running update:
```
node_modules/.bin/gemini update
(node:60437) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
✘ my react test initial [chrome]
Could not find element with css selector specified in setCaptureElements: [data-gemini-react] > *
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0
```

Browser opened blank page and closed it immediately.
I assume, that component not mounted at all :(
What can be wrong? Webpack config or missed babel-presets?

**Comment by SevInf** [comment]
Hi. Sorry for the late response. Could you please run `./node_modules/.bin/gemini-react-server`, navigate to the test page (it is basically url encoded suite names) and see if you've got any errors in browser console?

**Comment by dmitrika** [comment]
Thank you for reply!

Seems like bundle is not built. Css styles is available, but they served not from `/assets` dir.

```
GET http://127.0.0.1:5432/assets/gemini-test.bundle.js 404 (Not Found)
```

So, what I see with `cat .gemini-react-tmp/gemini-test.bundle.js`

```
window.geminiReact = require('../node_modules/gemini-react/lib/client-wrapper.js')();
require('../gemini/test.js')
   ```

Definitely have both modules available. Seems, like `/assets`  not served from `.gemini-react-tmp`

**Comment by SevInf** [comment]
Hm, interesting, that definetely should not happen. Can you post a reproduction repo on a github somewhere?

**Comment by dmitrika** [comment]
Hm, I in reproduction repo from div example and more. And now I understand, that when I add `stage-0` preset - everything is crashed as in my example.

Here demo-rep https://github.com/dmitrika/gemini-react

Now I'm googling why it could be so...

**Comment by dmitrika** [comment]
Thank you, I figured out, that the problem was in my `stage-0` preset. Actually I needed `transform-class-properties` only from `stage-2` actually, but I added it as a stand-alone plugin and it's ok :)
